# -*- coding: utf-8 -*-
"""simple linear regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c4okZPy_H7I8-Qd6ASrbwnLYclesXWSD
"""

import pandas as pd
import matplotlib.pyplot as plt

from sklearn import linear_model

from google.colab import files
files.upload()

data = pd.read_csv("student_scores.csv")

data

data.shape

plt.scatter(data['Hours'],data['Scores'])

data.plot(kind = 'line')
plt.show()

data.corr()

X = pd.DataFrame(data['Hours'])
Y = pd.DataFrame(data['Scores'])

lm = linear_model.LinearRegression()
model = lm.fit(X,Y)

model.coef_

model.intercept_

X = ([2.3,9.0,4.5])
X = pd.DataFrame(X)
Y = model.predict(X)
Y=pd.DataFrame(Y)
df = pd.concat([X,Y],axis=1,keys=['Hours','Scores'])
df

data.plot(kind='scatter',x='Hours',y='Scores')
plt.plot(X,model.predict(X),color='red')
plt.show()